#ifndef QTPRECOMPILED_H
#define QTPRECOMPILED_H

#include <QApplication>
#include <QMainWindow>
#include <QPushButton>
#include <QLabel>
#include <QLineEdit>
#include <QTextEdit>
#include <QComboBox>
#include <QListWidget>
#include <QListWidgetItem>
#include <QMessageBox>
#include <QFileDialog>
#include <QColorDialog>
#include <QFontDialog>
#include <QInputDialog>
#include <QProgressDialog>
#include <QDialog>
#include <QDialogButtonBox>
#include <QGroupBox>
#include <QRadioButton>
#include <QCheckBox>
#include <QSlider>
#include <QSpinBox>
#include <QDoubleSpinBox>
#include <QDateTimeEdit>
#include <QCalendarWidget>
#include <QFontComboBox>
#include <QTimeEdit>
#include <QDateEdit>
#include <QDial>
#include <QProgressBar>
#include <QScrollBar>
#include <QTableView>
#include <QTableWidget>
#include <QTableWidgetItem>
#include <QHeaderView>
#include <QTreeWidget>
#include <QTreeWidgetItem>
#include <QTabWidget>
#include <QStackedWidget>
#include <QSplitter>
#include <QFrame>
#include <QBoxLayout>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QFormLayout>
#include <QGridLayout>
#include <QSpacerItem>
#include <QSizePolicy>
#include <QScreen>
#include <QCursor>
#include <QStyle>
#include <QStyleOption>
#include <QStyleFactory>
#include <QIcon>
#include <QImage>
#include <QPixmap>
#include <QBitmap>
#include <QCursor>
#include <QPen>
#include <QBrush>
#include <QColor>
#include <QFont>
#include <QPalette>
#include <QBrush>
#include <QPen>
#include <QRegion>
#include <QPolygon>
#include <QPolygonF>
#include <QPoint>

#endif // QTPRECOMPILED_H